## 1. Write a NumPy program to create an array with the values 1, 7, 13, 105    and determine the size of the memory occupied by the array.


In [29]:
import numpy as np

In [30]:
arr = np.array([1,7,13,105])
print(f"Size = {arr.size}")

Size = 4


## 2. Write a NumPy program to create an element-wise comparison (greater,    greater_equal, less and less_equal) of two given arrays.

In [31]:
def function1():
    arr1 = np.array([11,5])
    arr2 = np.array([10,55])
    #print("Comparison - greater")
    print(f"Greater = {np.greater(arr1, arr2)}")
    print(f"Greater_Equal = {np.greater_equal(arr1,arr2)}")
    print(f"Less ={np.less(arr1, arr2)}")
    print(f"Less_Equal = {np.less_equal(arr1,arr2)}")

In [32]:
function1()

Greater = [ True False]
Greater_Equal = [ True False]
Less =[False  True]
Less_Equal = [False  True]


## 3.  Write a NumPy program to create an array of 10 zeros, 10 ones, 10    fives, 10 tens, 10 twentys and 10 fiftys.

In [33]:

arr1 = np.zeros(10)
print(f"10 Zeros = {arr1}")

arr2 = np.ones(10)
print(f"10 Ones = {arr2}")

arr3 = np.ones(10)*5
print(f"10 Fives = {arr3}")

arr4 = np.ones(10)*10
print(f"10 Tens = {arr4}")

arr5 = np.ones(10)*20
print(f"10 Twentys = {arr5}")

arr6 = np.ones(10)*50
print(f"10 Fiftys = {arr6}")



10 Zeros = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
10 Ones = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
10 Fives = [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
10 Tens = [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
10 Twentys = [20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
10 Fiftys = [50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


## 4. Write a NumPy program to create an array of integers from 30 to 70.

In [34]:
arr = np.arange(30,71)
print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


## 5. Write a NumPy program to create an array of integers from 50 to 95.

In [35]:
arr = np.arange(50,96)
print(arr)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


## 6. Write a NumPy program to create an array of all even integers from 20 to 80.

In [36]:
arr = np.arange(20,81,2)
print(arr)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80]


## 7. Write a NumPy program to create an array of all odd integers from 20 to 80.

In [37]:
arr = np.arange(21,80,2)
print(arr)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


## 8. Write a NumPy program to generate an array of 15 random numbers from 10    to 40.

In [38]:
arr = np.random.randint(10,40,15) 
print(arr)

[18 34 34 24 27 27 19 18 19 33 28 11 30 39 37]


## 9. Write a NumPy program to generate an array of 10 random numbers from 30    to 50.

In [39]:
arr = np.random.randint(30,50,10) 
print(arr)

[38 42 45 40 39 45 48 48 34 36]


## 10. Write a NumPy program to generate an array of 20 random numbers from 50    to 90.

In [40]:
arr = np.random.randint(50,90,20) 
print(arr)

[83 55 74 77 68 88 86 67 68 76 67 61 76 89 83 66 81 76 72 70]


## 11. Create any two arrays & perform various mathematical operations.
    i.e. Addition, Substraction, Multiplication, Divide.

In [41]:
arr1 = np.array([54,25,95])
arr2 = np.array([11,22,33])
print(f"Addition = {arr1+arr2}")
print(f"Substraction = {arr1-arr2}")
print(f"Multiplication = {arr1*arr2}")
print(f"Division = {arr1/arr2}")

Addition = [ 65  47 128]
Substraction = [43  3 62]
Multiplication = [ 594  550 3135]
Division = [4.90909091 1.13636364 2.87878788]


## 12. Write a NumPy program to create a 3x4 matrix filled with values from 10     to 21.

In [42]:
a = np.arange(10, 22).reshape((3, 4))
print(f"3x4 Matrix :")
print(a)

3x4 Matrix :
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


## 13. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal     elements are 1, the rest are 0.

In [43]:
x = np.diag([1, 1, 1])
print(f"3x3 Matrix :")
print(x)

3x3 Matrix :
[[1 0 0]
 [0 1 0]
 [0 0 1]]


## 14. Write a NumPy program to find the number of rows and columns in a given     matrix. 

In [44]:
a = np.arange(10, 22).reshape((3, 4))
print(f"Number of rows and columns ={a.shape}")

Number of rows and columns =(3, 4)


## 15. Write a NumPy program to create a 5x5 zero matrix with elements on the     main diagonal equal to 1, 2, 3, 4, 5.

In [45]:
x = np.diag([1, 2, 3, 4, 5])
print(f"5x5 Zero Matrix :")
print(x)

5x5 Zero Matrix :
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


## 16. Write a NumPy program to create a 3x3x3 array filled with arbitrary     values.

In [46]:
x = np.random.random((3, 3, 3))
print(f"3x3 Array :")
print(x)

3x3 Array :
[[[0.72082349 0.70033647 0.26020983]
  [0.33687634 0.46814094 0.60515987]
  [0.10362058 0.23132519 0.92300171]]

 [[0.89959658 0.35948926 0.56796354]
  [0.01686987 0.51201863 0.95557815]
  [0.57851806 0.0419802  0.73116365]]

 [[0.31918295 0.88891975 0.78100492]
  [0.76929326 0.25703523 0.38808594]
  [0.12418905 0.0986923  0.96881295]]]


## 17. Write a NumPy program to create a 2x3x4 array filled with arbitrary     values.

In [47]:
arr=np.random.random((2,3,4))
print(f"2x3x4 Array: {arr}")

2x3x4 Array: [[[0.69841631 0.24856942 0.29442974 0.00768071]
  [0.98033964 0.52074182 0.97334293 0.06904569]
  [0.62939817 0.2310782  0.53593843 0.58031943]]

 [[0.99472699 0.68448284 0.92215713 0.74593205]
  [0.23433649 0.8070411  0.82097795 0.09523949]
  [0.29875162 0.78674537 0.29008356 0.91289959]]]


## 18. Write a NumPy program to convert a list of numeric values into a one-    dimensional NumPy array.

In [48]:
l = [12.23, 13.32, 100, 36.32]
a = np.array(l)
print(a)

[ 12.23  13.32 100.    36.32]


## 19. Write a NumPy program to create a 3x3 matrix with values ranging from 2     to 10.

In [49]:
x = np.arange(2, 11).reshape(3, 3)
print(f"3x3 matrix with values ranging from 2 to 10")
print(x)

3x3 matrix with values ranging from 2 to 10
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 20. Write a NumPy program to create an array with values ranging from 12 to 38.

In [50]:
arr = np.arange(12,38)
print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


## 21. Write a NumPy program to reverse an array (the first element becomes the last).

In [51]:
arr = np.array([54,25,95,22,82,33,65])
print(f"Reverse = {arr[::-1]}")

Reverse = [65 33 82 22 95 25 54]


## 22. Write a NumPy program to convert an data type into to a floating type.

In [52]:
a = [1, 2, 3, 4]
b = np.asfarray(a)
print(b) 


[1. 2. 3. 4.]


## 23. Write a NumPy program to convert a list array.

In [53]:
t = [1, 7, 0, 6, 2, 5, 6]
arr = np.array(t)
print(f"List :{t}")
print(f"Array :{arr}")

List :[1, 7, 0, 6, 2, 5, 6]
Array :[1 7 0 6 2 5 6]


## 24. Write a NumPy program to get the element-wise remainder of an array of division.

In [54]:
x = np.arange(7)
print(x)
# Computing the element-wise remainder of division by 5 and displaying the result
y = np.remainder(x,5) 
print(y)

[0 1 2 3 4 5 6]
[0 1 2 3 4 0 1]


## 25. Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3.

In [55]:
arr1=np.arange(20,50)
print(f"Remainder= {arr1%3}")

Remainder= [2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]
